# preset_local.R

appPreset <- list(
  dbms = "duckdb",
  oracleTempSchema = "",
  cohortDatabaseSchema = "main",
  cohortTable = "cohort",
  targetId = 1,
  comparatorId = 2,
  outcomeIds = "3",
  primaryOutcomeId = 3,
  targetJsonFile = "inst/cohorts/target.json",
  comparatorJsonFile = "inst/cohorts/comparator.json",
  outcomeJsonFiles = "inst/cohorts/outcome.json",
  cdmDatabaseSchema = "main",
  studyStartDate = "",
  studyEndDate = "",
  firstExposureOnly = TRUE,
  washoutPeriod = 183,
  removeSubjectsWithPriorOutcome = TRUE,
  priorOutcomeLookback = 99999,
  riskWindowStart = 1,
  riskWindowEnd = 30,
  startAnchor = "cohort start",
  endAnchor = "cohort start",
  removeDuplicateSubjects = "keep first",
  restrictToCommonPeriod = FALSE,
  ps_prior = 0.01,
  maxCohortSizeForFitting = 250000,
  psScreening_enabled = TRUE,
  psScreening_sampleSize = 10000,
  psScreening_topCovariates = 200,
  psScreening_seed = 123,
  adjustment_method = "stratification",
  caliper = 0.2,
  maxRatio = 1,
  trimFraction = 0.1,
  modelType = "cox",
  stratified = TRUE,
  outputFolder = "results",
  createCohorts = TRUE,
  saveIntermediateRds = TRUE,
  verbose = TRUE
)